# values.yaml
image:
  repository: wenyuan1010/health-check-exporter
  tag: v3.0
  pullPolicy: IfNotPresent

healthUrls: 
   - "http://iot-device-management.iot.svc.cluster.local:8080/actuator/health"
   - "http://iot-linkage-engine.iot.svc.cluster.local:8080/actuator/health"
   - "http://iot-linkage-engine.ioms-alm.svc.cluster.local:8080/actuator/health"
   - "http://iot-linkage.ioms-alm.svc.cluster.local:8080/actuator/health"
   - "http://10.4.0.123:8080"
timeoutSeconds: 5
labels: "iot2:,ioms-alm:"
service:
  type: ClusterIP
  ports: 
    port: 8080
    name: health-metric
  namespace: wenyuan-test

prometheus:
  enabled: true
  namespace: cattle-prometheus
  interval: 15s
  #scrapeTimeout: 10s
