apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: wenyuan-test
spec:
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
#    targetPort: metrics
#   protocol: TCP
  selector:
    app: {{ .Chart.Name }}