apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
  selector:
    app: {{ .Chart.Name }}