apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.prometheus.namespace }}
  labels:
   team: frontend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  namespaceSelector:
     matchNames:
       - {{ .Values.service.namespace }}
  endpoints:
    - port: {{ .Values.service.ports.name }}
      interval: {{ .Values.prometheus.interval }}