apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}
  namespace: cattle-prometheus
  labels:
   team: frontend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  namespaceSelector:
     matchNames:
       - wenyuan-test
  endpoints:
    - port: {{ .Values.service.ports.name }}
      interval: 15s